### PR TITLE
Current NE3 cannot be installed on Py27

### PR DESCRIPTION
**Pull request by wjaekim**
I needed to test NE3 for my project, but had errors during the installation. I found these errors are related to recent commits. Let me change the code to correct this problem.

1. The queue module is imported with a wrong name in **ne3compiler.py**; the name should be Queue with Py27 and queue with Py3.
2. Handling of division proposed by Robert at line 859 of **interp_generator.py** produces error messages.

After applying the changes that I pushed (tested in my local directory), NE3 is compiled with success now.

### CODE REVIEW

**Comment by wjaekim** [comment]
Okay, after some testing on Py27 and Py36, I give up. I do not have time to spend on this. I knew NE3 is under development, but just hoped it would work for my simple use. It appears that a lot of bugs and improvements need to be taken care of. I was only able to make the code compiled on both Python versions. But some simple use cases (e.g., examples in the README file) generate errors.

I hope this project will be in a usable state in the near future. I really need this!

**Comment by robbmcleod** [comment]
Hi Woojae,

I see the problem with Queue, that's an easy fix.  I've mostly re-written the test module now so I should push that soon. 

I'm a little more settled now (I just moved from Switzerland to Canada) so hopefully I will be able to start fixing some bugs.  It is in an alpha-state, however.

**Comment by wjaekim** [comment]
Thanks for the reply, Rob. I hope your transition is smooth.
NE3 is very exciting to me. I am in cognitive science and do a lot of computationalmodeling. I recently made a change of my modeling language from Matlab to Python. In this process, NE2 has been an indispensable tool. I tried Numba but found NE2 generally much faster for the type of computation I do. But I found that there are some limitations of NE2 that would prevent my code from running even faster:

- Without multi-line support, even some simple algorithms cannot be compiled and evaluated in a single call.
- Some functions that I need such as the error function family are not supported.
- Setup time for threading increases with the increase of CPU cores, which in turn increases the break-even point (this forces me to set the # of cores to a number less than available cores for some appllication).

According to your blog post, these are taken care of in NE3!  I really hope you can work on this as soon as possible. I can give feedback whenever I can by trying new commits, if that helps.

One suggestion is that a function would be great that saves and loads the cache dictionary so it can be used across new script calls.

**Comment by robbmcleod** [comment]
Closing after commit of 605753f2d7c1bd6b444d8cef5fb6f95ca52d36f1

**Pull request closed without merging**
