### PR TITLE
Clear the f_locals dict to avoid extra ref counts in the calling scop…

### PR DESCRIPTION
**Pull request by lgarrison**
…e.  Closes pydata/numexpr#310.

### CODE REVIEW

**Comment by robbmcleod** [comment]
I would do something like:

    local_dict_as_arg = bool(local_dict)
    try:
        # .... All previous code in here
    finally:
        if not local_dict_as_arg:
            local_dict.clear()

A `try` block doesn't need an `except` statement following it.

**Comment by lgarrison** [comment]
Makes sense, how's that?

**Comment by robbmcleod** [comment]
Looks good to me, and probably a big enough bug to justify a release.

**Comment by lgarrison** [comment]
Great!  And thanks for the quick turnaround on this.

**Comment by robbmcleod** [comment]
Thank you for the fix. It may take awhile to build the wheels now but I've got the 2.6.7 release in the pipeline.

**Pull request merged**
