### PR TITLE
Re-enable linux aarch64 builds

### PR DESCRIPTION
**Pull request by matham**
This re-enables the linux aarch64 builds to see if it finishes in a reasonable time.

### CODE REVIEW

**Comment by matham** [comment]
Looks like manylinux_aarch64 takes like half an hour. Building musllinux_aarch64 doubles it up. We can perhaps disable building musllinux_aarch64?

**Comment by matham** [comment]
Looks like musllinux_aarch64 actually fails the tests so maybe we shouldn't build it?

**Comment by robbmcleod** [comment]
> We can perhaps disable building musllinux_aarch64 if this is too long?

Yes that's a reasonable compromise. 30 minutes build time is ok to me, but hours leading to timeouts is not. Thanks for working on this, I've been having trouble keeping up with my volunteer commitments lately.

**Comment by matham** [comment]
>Yes that's a reasonable compromise. 30 minutes build time is ok to me, but hours leading to timeouts is not. 

Ok, disabled it.

>Thanks for working on this, I've been having trouble keeping up with my volunteer commitments lately.

Thanks for the project.

To make it easier I added sdist generation using [build](https://pypa-build.readthedocs.io/en/latest/). I also added automatic upload to github release page and to pypi when a git tag happens. This should make a release process easier. 

If you would like to keep the pypi upload as I added it, you'll need to go to pypi, generate an API token, and [add it to github secrets for this repo](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository). It should be named `PYPI_PASSWORD`. Secrets are not passed to PRs btw FYI. And anyway it is only set to happen on a tag. If you'd rather do the release/pypi upload manually, I can remove that part lmk.

**Comment by matham** [comment]
Looks like the wheels are now building in a pretty short amount of time once muslinux was removed.

**Review by robbmcleod — CHANGES_REQUESTED** [review]
Let's take out the publishing to PyPi please, NumExpr is a requirement of some big projects including `pandas` so I always like to inspect the wheels before uploading them manually.

**Comment by matham** [comment]
>Let's take out the publishing to PyPi please

Ok, done!

**Comment by robbmcleod** [comment]
All good thanks. Ping me if I don't build wheels in the next week.

**Pull request merged**
