### PR TITLE
Wheels and CI on Appveyor

### PR DESCRIPTION
**Pull request by andreabedini**
Hi there,

in a crusade to better the state of python scientific software packaging :-) I stumbled on numexpr. Basically I was trying to get PyTables to build and test on appveyor and numexpr was a dependency so I thought I'd do that first.

Here is a PR that implements building and testing numexpr on Appveryor. It adds the needed scripts to correctly set up VS compilers on Windows (not trivial apparently) and a simple patch for `stdint.h` which is missing on MSVC 2009.

Beside testing on Windows, this also builds binary wheels that can be uploaded on PYPI. This can be done either manually by the maintainers or automatically. If you are on Windows (I am not) you can test the wheels by downloading them from https://ci.appveyor.com/project/andreabedini/numexpr/build/1.0.7 (select a version and then check the "artefacts" tab).

I have a gut feeling that `setup.py` can be drastically simplified. I haven't touched it in this PR but experiments with setup.py can now be done easily on all(?) supported platforms.

Ping @FrancescAlted

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Looks very good.  Merging.

**Comment by FrancescAlted** [comment]
I am +10 on simplifying setup.py (or any other simplification :), so feel free to send a PR for that.  Thanks!

**Comment by andreabedini** [comment]
Thanks @FrancescAlted. I have always been wary of touching setup.py because I couldn't do tests on windows, but now I can :)

**Comment by FrancescAlted** [comment]
Sure.  We are trying to do the same thing for python-blosc:

https://github.com/Blosc/python-blosc/commit/1fbefad066f24af4721c9d84a8e5e2a11b7d8f5e

but we are having issues with appveyor (see comments above).  Did you need to do something special with your appveyor account?

**Comment by andreabedini** [comment]
@FrancescAlted I did nothing more than going to ci.appveyor.com and flicking the switch (new project -> github -> select repository). Do you have a link for the build logs? I can't find it.

**Comment by andreabedini** [comment]
extra question, any chance you are planning to upload numexpr wheels somewhere (perhaps even on pypi?) anytime soon. Just so I know where to pull numexpr wheels from when building pytables.

**Comment by FrancescAlted** [comment]
Andrea, you can find the logs here: https://ci.appveyor.com/project/FrancescAlted/python-blosc

And I a fine with uploading wheels of numexpr to pypi.

**Comment by FrancescAlted** [comment]
Hmm, maybe it would be better to give you administrative privileges for both the numexpr github and pypi repos.  Would you be up to this?

**Comment by andreabedini** [comment]
cool, sure. I have never put anything on pypi, I'll double check with you before committing crimes :)
ps: some day I'll need admin on PyTables too ;-)

**Comment by FrancescAlted** [comment]
Cool.  I only need your user name in PyPI and will give you admin privileges there.

**Comment by andreabedini** [comment]
I'm andreabedini there too

**Comment by FrancescAlted** [comment]
I added you as owner for tables and maintainer for numexpr.  Tell me if you
need something more.

2015-06-05 11:15 GMT+02:00 Andrea Bedini <notifications@github.com>:

> I'm andreabedini there too
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pydata/numexpr/pull/178#issuecomment-109213971>.
>



-- 
Francesc Alted

**Pull request merged**
