### PR TITLE
Add support for Apple silicon and simplify build

### PR DESCRIPTION
**Pull request by matham**
This creates wheels for Apple silicon arm64 and also simplifies the build. You don't need to list all python versions as cibw will take care of it.

### CODE REVIEW

**Comment by matham** [comment]
I ran the actions on my branch (because it needs to be approved first for this repo) and got the [wheels](https://github.com/matham/numexpr/actions/runs/2006488994).

I then tested an arm64 wheel on a M1 and it works:

```py
Desktop % python
Python 3.9.10 (main, Jan 15 2022, 11:40:53)
[Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.uname()
uname_result(system='Darwin', node='...', release='21.1.0', version='Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:24 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T8101', machine='arm64')
>>> import numpy as np
>>> import numexpr as ne
>>> a = np.arange(10)
>>> b = np.arange(0, 20, 2)
>>> c = ne.evaluate("2*a+3*b")
>>> c
array([ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72], dtype=int64)
```

**Comment by robbmcleod** [comment]
Thanks for the contribution.

**Comment by matham** [comment]
Would it be possible to make a release (if one isn't already planned)?

**Comment by robbmcleod** [comment]
Let me see if the arm64 builds for Linux are working any better than they were.

**Pull request merged**
