### PR TITLE
fix 2 bug in contains

### PR DESCRIPTION
**Pull request by shadchin**
During issue #230

### CODE REVIEW

**Comment by FrancescAlted** [comment]
Looks good to me.  Could you give a hint on the kind of speedup that you are getting for `stringcontains`?  That would help for adding an entry in the changelog.

**Comment by shadchin** [comment]
For example:
needle = 'bc'
haystack = 'a' * 1000 + 'bc' -> length haystack is 1002

- First  step: search needle[0] in haystack -> reduce length haystack to 2.
If not found needle[0] then return 0
- Second step: check needle is prefix of reduced haystack
- Third step: two way algorithm

Other words, speedup is try reduced length haystack

**Comment by shadchin** [comment]
I'm sorry, I accidentally closed

**Comment by FrancescAlted** [comment]
Well, I meant if you can provide an estimate of the speedup that you are seeing in your use cases.

**Comment by shadchin** [comment]
I will try provide an estimate :)

**Comment by shadchin** [comment]
Theoretically, it was nice, but there was no practical use, only in synthetic tests.
Also I had to completely abandon the strlen. The first option is only corrected case for contains('const', 'const'), for contains(var, 'const'), contains('const', var) or contains(var, var) we still get segmentation fault.

**Comment by shadchin** [comment]
Comments? Objections?

**Comment by FrancescAlted** [comment]
Sorry that this was left unattended for too long.  Merging.

**Pull request merged**
